In [ ]:
# req: display array of ones (3 rows and 4 columns) 

In [5]:
import numpy as np

In [3]:
array_of_ones = np.ones((3,4)) # in this case 3 denotes no. of rows and 4 no. of columns
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [11]:
print(array_of_ones_int)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# printing an empty array with 2 rows and 3 columns, used when we have no idea of the input

In [14]:
array_empty = np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#identity matrix - 1s are printed in diagonal form

In [16]:
array_eye = np.eye(3) # in 3 rows 1s are printed diagonally
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# to print array of even numbers from the range of numbers 1-10 

In [17]:
array_of_events = np.arange(2,20,2) # (start value, end value, stepcount)

array_of_events # prints even numbers starting from 2 and ends with 18 as last number is exclusive

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])