In [ ]:
# understanding numpy
# how to install numpy

In [1]:
!pip install numpy

In [2]:
!pip install numpy --upgrade # upgrading the numpy version

     |████████████████████████████████| 15.1MB 1.6MB/s eta 0:00:01
  Found existing installation: numpy 1.17.2
    Uninstalling numpy-1.17.2:
      Successfully uninstalled numpy-1.17.2


In [ ]:
# installation of new version of numpy complete

In [4]:
import numpy as np # alias name as np for numpy. np is industry wide practice as alias for numpy.

In [ ]:
# numpy is default datatype of array, it deals with array

In [10]:
array_one = np.array([1,2,3,4]) # creation of array and assigning values to array

array_one

array([1, 2, 3, 4])

In [11]:
type(array_one)

numpy.ndarray

In [ ]:
# What is the difference between array and list, what is preferred? Array
# array and list have similar features, array represented as round&square brackets and list as square brackets
# arrays are stored in vectors for processing the code which helps in faster execution
# arrays provide better implementation indexing

In [13]:
numbers = [1,2,3,4,5] # another way of representing arrays

array_two = np.array(numbers)

array_two

array([1, 2, 3, 4, 5])

In [ ]:
# req: create an array of zeroes with desired shape (x,y) where x = rows, y=columns

In [17]:
array_zeros = np.zeros((3,4)) # 3 rows with zeros and 4 columns with zeros have been displayed

array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])