In [1]:
import numpy as np

In [ ]:
# printing of numpy arrays

In [3]:
a = np.arange(6) # this sort of array is called as 1D array

print(a)

[0 1 2 3 4 5]


In [4]:
type(a)

numpy.ndarray

In [7]:
# this sort of array is called 2D array. arange(total numbers to be displayed), reshape(rows,columns) - 4*3=12

b = np.arange(12).reshape(4,3)

print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
b = np.arange(12).reshape(5,2)

print(b)

#the below error is due to the conflict in size and reshape values, array size is 12 but reshape value is 5*2=10

ValueError: cannot reshape array of size 12 into shape (5,2)

In [11]:
c = np.arange(24).reshape(2,3,4)

print(c)

#the below error is 3D array. There are 2 data sets with 3 rows and 4 columns.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# introduction to statistical concepts in array

In [12]:
test_scores = np.array([32.32,56.98,21.52,44.32,55.63,13.75,43.47,43.34])

In [13]:
# mean formula -----> displays average value

print('Mean vaue of the test scores')

print(np.mean(test_scores))

Mean vaue of the test scores
38.91625


In [15]:
# median -----> displays middle value of the given set of numbers

print('Median value of the test scores')

print(np.median(test_scores))

Median value of the test scores
43.405
