In [1]:
import numpy as np

In [ ]:
# basic operations in numpy

In [3]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [4]:
a+b #addition

array([15, 15, 15])

In [5]:
a*b #multiplication

array([50, 50, 50])

In [6]:
a/b # division, display numbers in decimals as the default datatype is float 

array([2., 2., 2.])

In [7]:
a-b #subtraction

array([5, 5, 5])

In [8]:
a%b # % is modulus operator which gives remainder as output

array([0, 0, 0])

In [9]:
a%3 # 'a' has value of 10 when divided by 3 the remainder is 1

array([1, 1, 1])

In [ ]:
# comparison operators

In [10]:
a<30

array([ True,  True,  True])

In [11]:
a>30

array([False, False, False])

In [12]:
a**2 # a square -----> 10*10=100

array([100, 100, 100])

In [13]:
a**3 # a cube ----- 10*10*10=1000

array([1000, 1000, 1000])

In [ ]:
# req: modify existing array values

In [14]:
a += 20 # here we are adding 20 to 'a' which has value of 10, sums upto 30

a

array([30, 30, 30])

In [15]:
b += a # here we are adding 'a' value to 'b' which has 5 a+b -----> 30+5 and the new value is stored in 'b'

b

array([35, 35, 35])

In [ ]:
# unary operators -----> system default functions

In [16]:
ages = np.array([12,15,18,20])

In [17]:
ages.sum() # sum of all values in the array list

65

In [18]:
ages.min() # prints minimum value in the array list

12

In [19]:
ages.max() # prints maximum value in the array list

20

In [20]:
# print numbers upto 12 in sequential order in 3 rows and 4 columns

numbers = np.arange(12).reshape(3,4)

numbers # by default print starts from '0' and ends with '11' since last number is always skipped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])